services:
  server:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app  # Bind your local code to the container
      - ./nodemon.json:/usr/src/app/nodemon.json  # Bind Nodemon config to the container
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
       - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080